"""picam_timelapse_app - Flask web interface for a Raspberry Pi timelapse camera.

Run directly for development:

    python app.py

or behind a production server (see README.md):

    waitress-serve --host=0.0.0.0 --port=8000 app:app
"""

from __future__ import annotations

import atexit
import logging
import os
import re
from typing import Any, Dict, Tuple

from flask import (
    Flask,
    Response,
    jsonify,
    redirect,
    render_template,
    request,
    send_from_directory,
    url_for,
)

import camera_manager
import settings_store
from camera_manager import (
    STATE_IDLE,
    STATE_STREAMING,
    STATE_TIMELAPSE,
    CameraError,
    CameraManager,
    InvalidStateError,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
PHOTO_DIR = os.environ.get("PICAM_PHOTO_DIR") or os.path.join(BASE_DIR, "photos")
SETTINGS_FILE = os.environ.get("PICAM_SETTINGS_FILE") or os.path.join(
    BASE_DIR, "settings.json"
)

logging.basicConfig(
    level=os.environ.get("PICAM_LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)-7s %(name)s: %(message)s",
)
log = logging.getLogger("picam")

app = Flask(__name__)

settings = settings_store.SettingsStore(SETTINGS_FILE)
camera = CameraManager(PHOTO_DIR, settings)

atexit.register(camera.shutdown)

# The page that belongs to each state; every GET is redirected to the page
# matching the current state, so the browser can never show a stale view.
STATE_ENDPOINTS = {
    STATE_IDLE: "page_settings",
    STATE_TIMELAPSE: "page_timelapse",
    STATE_STREAMING: "page_stream",
}

# Photo filenames are generated by us, but validate anyway before touching disk.
SAFE_PHOTO_NAME = re.compile(r"^[0-9]{8}_[0-9]{6}(_[0-9]{2})?\.jpg$")


def _redirect_to_current_state() -> Response:
    return redirect(url_for(STATE_ENDPOINTS[camera.state]))


def _template_context() -> Dict[str, Any]:
    return {
        "status": camera.status(),
        "settings": settings.get(),
        "awb_modes": settings_store.AWB_MODES,
        "stream_size": "%dx%d" % camera_manager.STREAM_SIZE,
        "limits": {
            "interval": (settings_store.INTERVAL_MIN, settings_store.INTERVAL_MAX),
            "exposure": (settings_store.EXPOSURE_MIN, settings_store.EXPOSURE_MAX),
            "gain": (settings_store.GAIN_MIN, settings_store.GAIN_MAX),
            "saturation": (
                settings_store.SATURATION_MIN,
                settings_store.SATURATION_MAX,
            ),
            "sharpness": (settings_store.SHARPNESS_MIN, settings_store.SHARPNESS_MAX),
            "colour_gain": (
                settings_store.COLOUR_GAIN_MIN,
                settings_store.COLOUR_GAIN_MAX,
            ),
        },
    }


# --- Pages ----------------------------------------------------------------

@app.route("/")
def index() -> Response:
    return _redirect_to_current_state()


@app.route("/settings")
def page_settings():
    if camera.state != STATE_IDLE:
        return _redirect_to_current_state()
    return render_template("settings.html", **_template_context())


@app.route("/timelapse")
def page_timelapse():
    if camera.state != STATE_TIMELAPSE:
        return _redirect_to_current_state()
    return render_template("timelapse.html", **_template_context())


@app.route("/stream")
def page_stream():
    if camera.state != STATE_STREAMING:
        return _redirect_to_current_state()
    return render_template("stream.html", **_template_context())


# --- API ------------------------------------------------------------------

def _payload() -> Dict[str, Any]:
    """Accept both a JSON body and a classic HTML form post."""
    if request.is_json:
        data = request.get_json(silent=True)
        if isinstance(data, dict):
            return data
        return {}
    return dict(request.form)


def _error(message: str, code: int) -> Tuple[Response, int]:
    return jsonify({"ok": False, "error": message, "status": camera.status()}), code


@app.get("/api/status")
def api_status():
    return jsonify({"ok": True, "status": camera.status()})


@app.get("/api/settings")
def api_get_settings():
    return jsonify({"ok": True, "settings": settings.get()})


@app.post("/api/settings")
def api_save_settings():
    raw = _payload()
    # Checkboxes are absent from a form post when unticked.
    if not request.is_json and "auto_exposure" not in raw:
        raw["auto_exposure"] = False
    saved = settings.update(raw)
    # If the live stream is running, retune it straight away so the user can
    # see the effect of the change in the viewfinder.
    camera.apply_live_settings()
    log.info("Settings updated: %s", saved)
    return jsonify({"ok": True, "settings": saved, "status": camera.status()})


@app.post("/api/timelapse/start")
def api_timelapse_start():
    try:
        camera.start_timelapse()
    except InvalidStateError as exc:
        return _error(str(exc), 409)
    except CameraError as exc:
        return _error(str(exc), 500)
    return jsonify(
        {"ok": True, "status": camera.status(), "redirect": url_for("page_timelapse")}
    )


@app.post("/api/timelapse/stop")
def api_timelapse_stop():
    try:
        camera.stop_timelapse()
    except InvalidStateError as exc:
        return _error(str(exc), 409)
    return jsonify(
        {"ok": True, "status": camera.status(), "redirect": url_for("page_settings")}
    )


@app.post("/api/stream/start")
def api_stream_start():
    try:
        camera.start_stream()
    except InvalidStateError as exc:
        return _error(str(exc), 409)
    except CameraError as exc:
        return _error(str(exc), 500)
    return jsonify(
        {"ok": True, "status": camera.status(), "redirect": url_for("page_stream")}
    )


@app.post("/api/stream/stop")
def api_stream_stop():
    try:
        camera.stop_stream()
    except InvalidStateError as exc:
        return _error(str(exc), 409)
    return jsonify(
        {"ok": True, "status": camera.status(), "redirect": url_for("page_settings")}
    )


# --- Media ----------------------------------------------------------------

@app.get("/video_feed")
def video_feed():
    """MJPEG stream, valid only while in the STREAMING state."""
    if camera.state != STATE_STREAMING:
        return _error("The live stream is not running.", 409)
    response = Response(
        camera.mjpeg_frames(),
        mimetype="multipart/x-mixed-replace; boundary=frame",
    )
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate"
    response.headers["Age"] = "0"
    return response


@app.get("/photos/<path:filename>")
def photo(filename: str):
    if not SAFE_PHOTO_NAME.match(filename):
        return _error("Not a valid photo name.", 400)
    if not os.path.isfile(os.path.join(camera.photo_dir, filename)):
        return _error("Photo not found.", 404)
    return send_from_directory(camera.photo_dir, filename, max_age=0)


@app.get("/api/last_photo")
def api_last_photo():
    """Redirect to the most recent photo taken in this timelapse run."""
    last = camera.status()["last_photo"]
    if not last:
        return _error("No photo has been taken yet.", 404)
    return redirect(url_for("photo", filename=last))


@app.errorhandler(404)
def not_found(_exc):
    if request.path.startswith("/api/"):
        return _error("Unknown endpoint.", 404)
    return _redirect_to_current_state()


if __name__ == "__main__":
    host = os.environ.get("PICAM_HOST", "0.0.0.0")
    port = int(os.environ.get("PICAM_PORT", "8000"))
    log.info("Photos are saved to %s", camera.photo_dir)
    log.info("Settings file: %s", SETTINGS_FILE)
    if not camera_manager.PICAMERA2_AVAILABLE:
        log.warning("Running with the MOCK camera (picamera2 not importable).")
    # threaded=True is required: the MJPEG response occupies one worker for as
    # long as the browser keeps the viewfinder open.
    app.run(host=host, port=port, threaded=True, debug=False, use_reloader=False)
